const names = require('./4-name')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavor')
console.log(data)
require('./7-mind-grenade')
sayHi('susan')
sayHi(names.jhon)
sayHi(names.peter)